---
title: "M-OPC"
format: html
---

## **Mumbai - Online Psychometrics Centre (M-OPC)**

I have developed Mumbai Online Psychometrics Centre. The psychological instruments developed include MUPI (Mumbai University Personality Inventory), MUII (Mumbai University Interest Inventory), Mumbai University -General Ability Test, and Mumbai University-Aptitude Test Battery, etc. in Indian languages. This is available in an online mode. Reports are available to each participant/ test taker in Indian language. Developed a web-based system and computerized system for reports generation. (See [Sample Report](https://drive.google.com/file/d/1eYbKfDUgeepczFX4WgaEbw-g5cXuEwgl/view?usp=share_link))

Personality Assessment: MUPI\
Interest Assessment: MUII 

## **MUPI: Mumbai University Personality Inventory**

MUPI is developed using Big-Five and Beyond Approach (BFBA).

Full version has 300 items. It has Short version of 100 items, 50 items, 30 Items, and 10 Items. Full version assesses 65 facets of personality.

It controls for response bias and inattention bias.

It is developed by Vivek Belhekar and Radhika Bhargava.

## **MUII: Mumbai University Interest Assessment**

MUII is developed combining RIASEC and OVIS.

Full version has measures Activities, Competencies, and Occupations. Short version only reports activities subscale.

It is developed by Vivek Belhekar and Tanya Keni.

## Use M-OPC

To know more or take a test for yourself, visit <https://m-opc-onlinepsychometrics.share.connect.posit.cloud/home.html>
