---
title: "Seminars, Workshops, Lectures"
format: html
---

## **National Workshops Designed and Conducted**

**National Seminar** on the occasion of Gandhi Jayanti. Mahatma Gandhi Peace Centre, University of Mumbai. October 2, 2023.

**National Seminar** conducted online on the occasion of *Gandhi Punyatithi* (Martyrs' Day) by Mahatma Gandhi Peace Centre (MGPC), University of Mumbai, for Sharing Initial findings of the project “**Lexical Gandhi**”. January 30, 2023.

Designed and Conduced **Three Day National Workshop** for **‘Machine Learning for Businesses and HR Research’** 28 March 2022 to 30 March 2022 for Samaya University.

**Applications Of Statistical Methods For Research In Psychology And Behavioural Sciences: Hand’s on Training using R**. Three-Day Workshop at Amity University, Mumbai Feb 2018.

National workshop on “**Statistical analysis using R**” at University of Mumbai.

Two National workshops on “**Structural Equations Modelling**” at University of Mumbai. (31 Jan – 01 Feb 2015; March 2017).

Designed and Conducted One National workshop on “**Experiment Building using computers**” at University of Mumbai. July 2016.

Designed and Conducted National workshops on “**Statistical analysis using R**” at Mizoram Central University, Aizawl, Mizoram.

Designed and Conducted Four-Day Workshop on “**Machine Learning using R**” at Ho Chi Minh City, Vietnam.

Designed and conducted two-day national workshops on “**Machine Learning using R**” at Somaiya University, Mumbai.

Designed and conducted a two-day Workshop on **Soft-Skills and Leadership Skills** for Range-Forest Officers (RFO) in Tadoba National Park, Chandrapur, Maharashtra.

Designed and conducted a two-day Workshop on **Soft-Skills and Leadership Skills** for Range-Forest Officers (RFO) in Melghat National Park, Chandrapur, Maharashtra.

## **Refresher Courses and Short Term Courses Designed and Coordinated**
