---
title: "Teaching"
format: html
---

# **Masters Course (2024-25)**

**SEMESTER I:**

-   Personality Psychology

-   Statistics for Psychology

-   Experimental Psychology- Practical

-   Psychopathology

**SEMESTER II:**

-   Evolutionary Psychology

-   Psychological Testing and Psychometrics - Practical

**SEMESTER III:**

-   Data Analytics and Machine Learning applications to Psychology

-   Clinical Psychology – Field based Practical Course

**SEMESTER IV:**

-   Cultural Psychology

-   Psychology for Conservation and Climate Change

# **PhD**

I work in the area of personality and culture with emphasis on lexical approach and psychology for conservation and climate change in India.

[**Degree Awarded = 02**]{.underline}

-   **Korgaonkar Aditi Vijay Smita**

**Title**: An Experimental Investigation on Affect and Perception about Help and Helpers: Effects

of Stability and Power Relations on Intergroup help seeking

-   **Dittakavi Shri Snigdha**

**Title**: Personality Profiles of Individuals with and without Substance Dependence: A Comparative Study using the Five-Factor Model (FFM) of Personality and Personality Disorder Traits

[**Thesis Submitted = 01**]{.underline}

-   **Shinde Meet Dnyaneshwar Tara**

Title: A Psychological Exploration of the Non-Dalit’s Schema of Dalits and the Dalits’ Urban Experiences of Caste-based Discrimination: A Grounded Theory based Enquiry

[**Currently Registered = 04**]{.underline}

-   **Trupti Nawar** (Synopsis Submitted)

**Title:** Psycho-Lexical and Psychometric Investigation of Dimensionality of Cognitive Styles with Ability and Personality

-   **Radhika Bhargava (UGC-JRF)**

**Title:** A Psycholexical Investigation of Interpersonal Trait Descriptors among Hindi Speakers

-   **Chaitra Deshpande (UGC-JRF)**

**Title:** Understanding the Personality Structure of Katkari Tribe in Maharashtra employing the Psycholexical Approach

-   **Sitara Menon**

**Title:** The Structure of Human Values Among Malayalam Language Speakers: A Psycholexical Investigation

[**Assigned: 02**]{.underline}

-   **Jayesh Shinde (UGC-JRF)**

-   **Sailee Shinde**

**Current Vacancy for PhD: Zero**
